### ISSUE TITLE
feedback link selector not consistent

### ISSUE THREAD

**Issue by joshmanders** [shellscape/github-notifications-classic#1]
- Browser Name and Version: Brave Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
- github-notifications-classic Version: commit sha `51b8e1e`

### Screenshot of Problem

![image](https://user-images.githubusercontent.com/352113/80156335-4736aa00-8589-11ea-89fa-20abd965e9aa.png)

### Expected Behavior
The "Give us feedback" link should be gone

### Actual Behavior
The "Give us feedback" link is visible

This is because the selector
```css 
div[data-channel="notification-changed:76371"] { display: none; }
```
has a number dependency which is not a constant through everyone, for example in my link, the number in `notification-changed:*` is `352113`

I tried a few ways to make it work agnostic of that value but was fruitless. Filing bug issue in hopes someone smarter with CSS can figure it out.

**Comment by shellscape** [comment]
OK I'll have to use an uglier selector for that then. Thanks for letting me know.
